version: '2.3'
services:
  app:
    image: localhost:8082/de.kvwl.test/simplewebapp:0.0.1-SNAPSHOT
    ports:
    - "9090:8080"
#    depends_on:
#    - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/simplewebapp"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    networks:
    - db

  db:
    image: postgres
    ports:
    - "5432:5432"
#    expose:
#    - "5432"
    environment:
    - POSTGRES_PASSWORD=reverse
    networks:
      db:
        aliases:
        - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  test:
    image: localhost:8082/de.kvwl.test/simplewebapp-test:0.0.1-SNAPSHOT
    depends_on: [ db ]
    networks: [ db ]

networks:
  db:
